[platformio]
default_envs = devel
include_dir = src

[env]
;platform = espressif32 ; Core v3.x
platform = espressif32 @ 6.13.0 ; = Arduino v2.0.17, IDF v5.5.3
; platform = https://github.com/pioarduino/platform-espressif32.git 
platform_packages =
	;framework-arduinoespressif32 @ ~3.20017.0 ; v2.0.17
;framework = espidf, arduino ; dual framework model
framework = arduino
board = esp32-c3-devkitm-1 ; ESP32-C3 Super Mini
board_build.partitions = ota_nofs_4MB.csv
extra_scripts = 
	pre:build_timestamp.py ; inject BUILD_TIMESTAMP define
	post:replace_bootloader.py ; replace with our own rollback-enabled one
lib_deps = 
	Wire
	SPI
	; moononournation/GFX Library for Arduino // OK with Core v3.x
	moononournation/GFX Library for Arduino @ 1.6.1 ; https://github.com/moononournation/Arduino_GFX/issues/742
	;pierremolinaro/ACAN_ESP32 ; Core v3.x
    pierremolinaro/ACAN_ESP32 @ 1.1.2 ; Core v2.x
	mathertel/OneButton @ ^2.6.2
	; h2zero/NimBLE-Arduino
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	default
;upload_port = /dev/ttyACM0
;monitor_port = /dev/ttyACM0

[common]
build_unflags = -std=gnu++11 ; default Arduino C++ standard takes precedence over build_flags
build_flags = 
    -I./include
	'-DORD_NAME="Open Ride Dash"'
	'-DORD_VERSION="0.1.1"'
	-DORD_BOARD=c3_supermini
	-DORD_DISPLAY=st7789_240x240
	-std=gnu++17 ; allow features up to C++17: structured bindings, if-constexpr, inline variables, etc.
    -DARDUINO_USB_MODE=1 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSE_ESP_IDF_LOG ; required for esp_log_set_vprintf()
    -DTAG="\"Arduino\"" ; Catch-all for ESP_LOGx on Core v2.x
	-DCONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1 ; enable OTA rollback 
	
[devel]
build_unflags = ${common.build_unflags}
build_flags = 
	${common.build_flags}
	'-DBUILDTAG="dev"'
	;-DCORE_DEBUG_LEVEL=1 ; 0: none, 1: error, 2: warning, 3, info, 4: debug, 5: verbose
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
	-DFEATURE_SERIAL
	;-DCONFIG_BT_NIMBLE_LOG_LEVEL=3 ; 0 = DEBUG, 1 = INFO, 2 = WARNING, 3 = ERROR, 4 = CRITICAL, 5+ = NONE
	;-DCONFIG_NIMBLE_CPP_LOG_LEVEL=1 ; 0 = NONE, 1 = ERROR, 2 = WARNING, 3 = INFO, 4+ = DEBUG
	;-DCONFIG_NIMBLE_CPP_ENABLE_RETURN_CODE_TEXT ; return codes as text
	;-DCONFIG_NIMBLE_CPP_ENABLE_GAP_EVENT_CODE_TEXT ; GAP event codes as text
	;-DCONFIG_NIMBLE_CPP_ENABLE_ADVERTISEMENT_TYPE_TEXT ; advertisement types as text
	;-DENABLE_I2C_DEBUG_BUFFER

[prod]
build_unflags = ${common.build_unflags}
build_flags = 
	${common.build_flags}
	'-DBUILDTAG="prod"'
	-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_ERROR
	;-DFEATURE_SERIAL
	;-DCORE_DEBUG_LEVEL=1 ; 0: none, 1: error, 2: warning, 3, info, 4: debug, 5: verbose
	;-DCONFIG_BT_NIMBLE_LOG_LEVEL=5 ; 0 = DEBUG, 1 = INFO, 2 = WARNING, 3 = ERROR, 4 = CRITICAL, 5+ = NONE
	;-DCONFIG_NIMBLE_CPP_LOG_LEVEL=0 ; 0 = NONE, 1 = ERROR, 2 = WARNING, 3 = INFO, 4+ = DEBUG

[env:devel]
lib_deps = ${env.lib_deps}
build_unflags = ${devel.build_unflags}
build_flags = ${devel.build_flags}
build_type = debug

[env:develOTA]
lib_deps = ${env.lib_deps}
build_unflags = ${devel.build_unflags}
build_flags = ${devel.build_flags}
build_type = debug
upload_protocol = espota
upload_port = ord-dev.local

[env:prod]
lib_deps = ${env.lib_deps}
build_unflags = ${prod.build_unflags}
build_flags = ${prod.build_flags}

[env:prodOTA]
lib_deps = ${env.lib_deps}
build_unflags = ${prod.build_unflags}
build_flags = ${prod.build_flags}
upload_protocol = espota
;upload_port = ord-prod.local
upload_port = ord-dev.local
